### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by stevekludt** [hdinsight/spark-eventhubs#1]
I am getting the following error message when I try to use the eventhubs.EventHubsUtils.  I am using a local instance of Spark to develop against and cannot get my stream to run against Event Hubs.

any help would be greatly appreciated.

Exception in thread "main" java.lang.NoClassDefFoundError: com/microsoft/eventhubs/client/IEventHubFilter
    at org.apache.spark.streaming.eventhubs.EventHubsUtils$.createStream$default$6(EventHubsUtils.scala:80)
    at org.apache.spark.streaming.eventhubs.EventHubsUtils$$anonfun$1.apply(EventHubsUtils.scala:58)
    at org.apache.spark.streaming.eventhubs.EventHubsUtils$$anonfun$1.apply(EventHubsUtils.scala:58)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.Range.foreach(Range.scala:141)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.apache.spark.streaming.eventhubs.EventHubsUtils$.createUnionStream(EventHubsUtils.scala:57)
    at main.scala.com.datuh.spark.ConnectToEH$.createContext(ConnectToEH.scala:33)
    at main.scala.com.datuh.spark.ConnectToEH$$anonfun$1.apply(ConnectToEH.scala:69)
    at main.scala.com.datuh.spark.ConnectToEH$$anonfun$1.apply(ConnectToEH.scala:68)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.streaming.StreamingContext$.getOrCreate(StreamingContext.scala:633)
    at main.scala.com.datuh.spark.ConnectToEH$.main(ConnectToEH.scala:67)
    at main.scala.com.datuh.spark.ConnectToEH.main(ConnectToEH.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: java.lang.ClassNotFoundException: com.microsoft.eventhubs.client.IEventHubFilter
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 21 more

**Comment by arijitt** [comment]
This is no longer an issue. So closing it.
