### ISSUE TITLE
Spark job crashes with different exceptions

### ISSUE THREAD

**Issue by devendrasr** [hdinsight/spark-eventhubs#416]
I am trying to consume events from eventhub and I am getting below exceptions frequently - 

Job aborted due to stage failure: Task 1 in stage 28.0 failed 4 times, most recent failure: Lost task 1.3 in stage 28.0 (TID 2323, 10.139.64.6, executor 0): java.util.concurrent.CompletionException: com.microsoft.azure.eventhubs.ReceiverDisconnectedException: New receiver with higher epoch of '0' is created hence current receiver with epoch '0' is getting disconnected. If you are recreating the receiver, make sure a higher epoch is used. TrackingId:d624026200011a0e00044a505c0047bb_G11_B11, SystemTracker:eventhub-dev:eventhub:dev01~16383|cg01, Timestamp:2018-11-29T20:10:40, errorContext[NS: eventhub-dev.servicebus.windows.net, PATH: dev01/ConsumerGroups/cg01/Partitions/1, REFERENCE_ID: f7fa63_c2c_G11_1543522225931, PREFETCH_COUNT: 2000, LINK_CREDIT: 2000, PREFETCH_Q_LEN: 0]

And sometimes I am getting an exception around this - 

18/11/29 19:45:07 WARN TaskSetManager: Lost task 0.0 in stage 11.0 (TID 448, 10.139.64.8, executor 0): 
java.lang.IllegalStateException: In partition 0 of dev01, 
with consumer group cg01, request seqNo 15366 is less than 
the received seqNo 14967. The earliest seqNo is 0 and the last seqNo is 15397

Can you please help me out on this? I am using below dependency version - 

```
com.microsoft.azure:azure-eventhubs-spark_2.11:2.3.6
```

**Comment by devendrasr** [comment]
Check this:

java.lang.IllegalStateException: In partition 1 of dev01, with consumer group cg02, request seqNo 31557 is less than the received seqNo 31564. The earliest seqNo is 0 and the last seqNo is 31588 	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.checkCursor(CachedEventHubsReceiver.scala:115) 	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver.org$apache$spark$eventhubs$client$CachedEventHubsReceiver$$receive(CachedEventHubsReceiver.scala:130) 	at org.apache.spark.eventhubs.client.CachedEventHubsReceiver$.receive(CachedEventHubsReceiver.scala:179) 	at org.apache.spark.eventhubs.rdd.EventHubsRDD.compute(EventHubsRDD.scala:122) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:42) 	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:336) 	at org.apache.spark.rdd.RDD.iterator(RDD.scala:300) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:96) 	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:53) 	at org.apache.spark.scheduler.Task.run(Task.scala:112) 	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:384) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 	at java.lang.Thread.run(Thread.java:748)



I am getting such exceptions in the middle of the job. This is frustrating.
