### ISSUE TITLE
NoSuchMethodException exception while using ServicePrincipal authentication to EventHub

### ISSUE THREAD

**Issue by pchinta** [hdinsight/spark-eventhubs#625]
Thanks for filing an issue with us! Below are some guidelines when filing an issue. In general, the more detail the better!

Feature Requests: 

- What issue are you trying to solve?  - ServicePrincipal to authenticate to EventHub using Scala
- How do you want to solve it?  -
- What is your use case for this feature?  Following the documentation, writing scala code to authenticate to EventHubs using ServicePrincipal and getting NoSuchMethodException -  https://github.com/Azure/azure-event-hubs-spark/blob/master/docs/use-aad-authentication-to-connect-eventhubs.md

StreamingSelectDF  failing with NoSuchMethodException - 

val connectionString = ConnectionStringBuilder().setAadAuthConnectionString(new URI("xxxxx.servicebus.windows.net"), "testing").build
  
val ehConf = EventHubsConf(connectionString)
  .setConsumerGroup("consumerGroup")
  .setAadAuthCallback(AuthBySecretCallBack())
var streamingInputDF = 
  spark.readStream
    .format("eventhubs")
    .options(ehConf.toMap)
    .load()

var streamingSelectDF = 
  streamingInputDF
   .select(get_json_object(($"body").cast("string"), "$.zip").alias("zip"))
    .groupBy($"zip") 
    .count()
val query =
  streamingSelectDF
    .writeStream
    .format("console")        
    .outputMode("complete") 
    .trigger(ProcessingTime("25 seconds"))
    .start()

Bug Report:

- Actual behavior  -   Getting NoSuchMethodException - 
java.lang.NoSuchMethodException: $line7cadbb75eb9f4bc88218baef4e0b427325.$read$$iw$$iw$$iw$$iw$$iw$$iw$AuthBySecretCallBack.&lt;init&gt;()
               at java.lang.Class.getConstructor0(Class.java:3082)
               at java.lang.Class.getConstructor(Class.java:1825)
               at org.apache.spark.eventhubs.EventHubsConf.$anonfun$aadAuthCallback$3(EventHubsConf.scala:632)
               at scala.Option.map(Option.scala:230)
               at org.apache.spark.eventhubs.EventHubsConf.aadAuthCallback(EventHubsConf.scala:630)
               at org.apache.spark.eventhubs.client.ClientConnectionPool.$anonfun$borrowClient$6(ClientConnectionPool.scala:73)
               at org.apache.spark.eventhubs.utils.RetryUtils$.$anonfun$retryJava$1(RetryUtils.scala:91)
               at org.apache.spark.eventhubs.utils.RetryUtils$.org$apache$spark$eventhubs$utils$RetryUtils$$retryHelper$1(RetryUtils.scala:116)
               at org.apache.spark.eventhubs.utils.RetryUtils$.retryScala(RetryUtils.scala:149)
               at org.apache.spark.eventhubs.utils.RetryUtils$.retryJava(RetryUtils.scala:91)

- Expected behavior - Expected to stream from EventHub
- Spark version  -  Apache Spark 3.1.2, Scala 2.12
- spark-eventhubs artifactId and version  - com.microsoft.azure:azure-eventhubs-spark_2.12:2.3.21

**Comment by nikhilbaby** [comment]
Where you able to find whats the reason for the method error. I'm trying the same in Pyspark.
